apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: keycloak-client-crd
namespace: auth
labels:
- pairs:
    app.kubernetes.io/part-of: keycloak
    app.kubernetes.io/component: auth
    app.kubernetes.io/name: client
resources:
- definition.yaml
- composition.yaml
